name: Blog Bug Report
description: File a bug report relating to a blog post on gamemaker.io
type: 'Docs Bug'
labels: ["Blogs"]
projects: ["YoYoGames/17"]
assignees: ["gurpreetsinghmatharoo"]
body:
  - type: markdown
    attributes:
      value: |
        Search for existing reports of this bug first! If one exists, DO NOT send your own report, instead leave a thumbs-up/comment on the existing one.

        Both fields need to be filled-in before you can submit this report, as it's required information so we can confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: What is the bug?
      description: Write a thorough description of the issue. You may paste screenshots at suitable locations in your text.
    validations:
      required: true
      
  - type: input
    id: link
    attributes:
      label: Where is the bug?
      description: Please add a link to the relevant blog post here
    validations:
      required: true
 
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
