blank_issues_enabled: false
contact_links:
  - name: Extension Docs Bugs/Requests
    url: https://github.com/orgs/YoYoGames/repositories?language=&q=gmext&sort=name
    about: Please report anything regarding extension documentation in the specific bug tracker for that extension - follow the link here to find the correct place.
  - name: GameMaker Bugs
    url: https://github.com/YoYoGames/GameMaker-Bugs/issues
    about: Do not report general GameMaker issues in this documentation space - instead, follow the link here to report them properly.
  - name: GameMaker Account Support
    url: https://contact.gamemaker.io/contact-us
    about: Contact the Helpdesk if you are having trouble with your GameMaker account.
