on:
    workflow_dispatch:
    pull_request:
      branches:
        - main-lts
    
env:
     S3_BUCKET: ${{ secrets.S3_BUCKET }}
     ZIP_FILE: ${{ secrets.ZIP_FILE }}
    
jobs:
    
       RoboHelp:
         name: "RoboHelp"
         runs-on: windows-2019
         steps:
          - uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.REGION }}
          - name: Enable git long paths to bypass path limit on Windows
            run: git config --system core.longpaths true
          - name: Check out the GMS2_Documentation repo
            uses: actions/checkout@v4
            with:
              path: Manual  
              token: ${{ secrets.GH_TOKEN }}
          - name: LTS Builds
            run: build_robohelp_gh.bat %GITHUB_WORKSPACE%\output
            shell: cmd
            working-directory: Manual       
          - name: Upload robohelp zip file
            uses: actions/upload-artifact@v4
            with:
               name: YoYoStudioRoboHelp
               path: output\RoboHelp\*.zip
               if-no-files-found: error
    