name: Main

on:
    workflow_dispatch:
    pull_request:
      branches:
        - main  
  
env:
   S3_BUCKET: ${{ vars.MANUAL_S3_BUCKET }}
   ZIP_FILE: ${{ vars.MANUAL_ZIP_FILE }}
   GITHUB_REPOSITORY: ${{ github.repository }}

permissions:
  contents: read
  id-token: write
  
jobs:
  
     RoboHelp:
       name: "RoboHelp"
       runs-on: windows-2022
       env:
        LANGUAGE: ${{ vars.LANGUAGE }}
       steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            role-session-name: github-actions-s3-downloadload-${{ github.run_id }}
            role-to-assume: ${{ vars.CORETECH_ASSUME_ROLE_ARN }}
            aws-region: eu-west-1  
        - name: Enable git long paths to bypass path limit on Windows
          run: git config --system core.longpaths true
        - name: Check out the GMS2_Documentation repo
          uses: actions/checkout@v6
          with:
            path: Manual  
            token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        - name: Monthly Builds
          if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
          env:
            BUILDBETA: '0'
          run: build_robohelp_gh.bat %GITHUB_WORKSPACE%\output
          shell: cmd
          working-directory: Manual
        - name: Upload robohelp zip file
          uses: actions/upload-artifact@v7
          with:
             name: YoYoStudioRoboHelp
             path: output\RoboHelp\*.zip
             if-no-files-found: error
  
