name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:

concurrency:
  group: upstream-sync-${{ github.repository }}
  cancel-in-progress: false

jobs:
  sync_latest_from_upstream_develop:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo to develop branch

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false

      - name: Merge from upstream
        env:
          UPSTREAM: YoYoGames/GameMaker-Manual
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git remote add upstream "https://x-access-token:${GH_TOKEN}@github.com/${UPSTREAM}.git"
          git fetch upstream develop
          git merge -X ours upstream/develop

      - name: Push changes to develop
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          branch: develop


  sync_latest_from_upstream_2026_main:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo to 2026.0.0-main branch

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          ref: 2026.0.0-main
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false

      - name: Merge from upstream
        env:
          UPSTREAM: YoYoGames/GameMaker-Manual
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git remote add upstream "https://x-access-token:${GH_TOKEN}@github.com/${UPSTREAM}.git"
          git fetch upstream 2026.0.0-main
          git merge -X ours upstream/2026.0.0-main

      - name: Push changes to 2026.0.0-main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          branch: 2026.0.0-main