name: Upstream Sync Reusable

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      upstream_branch:
        required: true
        type: string
      upstream_repo:
        required: false
        type: string
        default: YoYoGames/GameMaker-Manual
    secrets:
      GH_TOKEN:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Merge from upstream
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          UPSTREAM_REPO: ${{ inputs.upstream_repo }}
          UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
        run: |
          set -e

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git remote add upstream "https://x-access-token:${GH_TOKEN}@github.com/${UPSTREAM_REPO}.git"
          git fetch upstream "${UPSTREAM_BRANCH}"
          git merge -X ours "upstream/${UPSTREAM_BRANCH}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ inputs.target_branch }}